name: Release

on:
  push:
    tags:
      - "v*.*.*"  # Runs only when a version tag (e.g., v1.0.0) is pushed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history for proper versioning

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean  # Updated from "--rm-dist"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
